# Standard answers and internal state managed by Copier
_commit: v2.4.0-39-gc3c230c
_src_path: ~/src/steve-downey/exemplar/copier
description: Free Function constrained `value_or`
maintainer: steve-downey
minimum_cpp_build_version: '20'
paper: PnnnnRr
project_name: free_value_or
unit_test_library: catch2
# Hidden variables manually tracked because 'when: false' omits them from _copier_answers
generating_exemplar: false
owner: "bemanproject"
ci_tests_cron: "11 7 * * 2"
pre_commit_update_cron: "53 4 * * 3"
